import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.event.ChangeListener;

public class ImageAdjuster extends javax.swing.JDialog {
    private int brightness = 50;
    private int contrast = 50;
    private boolean inverted = false;
    private boolean resetPressed = false;
    private JFrame parent;
    //private boolean brightUsed = true;
    //private boolean contrastUsed = true;
    /** Creates new form ImageAdjusterB */
    
    public ImageAdjuster(JFrame parentFrame, boolean modal) {
        super(parentFrame, modal);
        parent = parentFrame;
        getRootPane().getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE,0),"CloseWindow");
        getRootPane().getActionMap().put("CloseWindow", new AbstractAction(){
            public void actionPerformed(ActionEvent e){
                setVisible(false);
            }
        });
        initComponents();
    }

    void popupReset(){
        popup(brightSlider.isEnabled(),50,contrastSlider.isEnabled(),50,false);
    }
    void popup(){
        setLocationRelativeTo(parent);
        resetPressed = false;
        setVisible(true);
    }
    void popup(int bright,int contrst,boolean invert){
        popup(true,bright,true,contrst,invert);
    }
    void popup(boolean brightEnable, int bright, boolean contrEnable, int contrst, boolean invert){
        popup();
        brightSlider.setEnabled(brightEnable);
        brightSlider.setValue(bright);
        contrastSlider.setEnabled(contrEnable);
        contrastSlider.setValue(contrst);
        invertEnableBox.setSelected(invert);
    }
    boolean shouldReset(){
        return resetPressed;
    }

    int getBrightness(){
        //if(brightUsed)
            return brightness;
        //return 50;
    }
    int getContrast(){
        //if(contrastUsed)
            return contrast;
        //return 50;
    }
    boolean isInverted(){
        return inverted;
    }

    //Should pause slideshow?

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        contrastEnableBox = new javax.swing.JCheckBox();
        contrastSlider = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        brightEnableBox = new javax.swing.JCheckBox();
        brightSlider = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        invertEnableBox = new javax.swing.JCheckBox();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setTitle("Adjust Image");
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contrast"));

        contrastEnableBox.setSelected(true);
        contrastEnableBox.setText("Enabled");
        contrastEnableBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrastEnableBoxActionPerformed(evt);
            }
        });

        contrastSlider.setMajorTickSpacing(25);
        contrastSlider.setMinorTickSpacing(5);
        contrastSlider.setPaintLabels(true);
        contrastSlider.setPaintTicks(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contrastEnableBox)
                .addGap(18, 18, 18)
                .addComponent(contrastSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(contrastSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contrastEnableBox))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Brightness"));

        brightEnableBox.setSelected(true);
        brightEnableBox.setText("Enabled");
        brightEnableBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brightEnableBoxActionPerformed(evt);
            }
        });

        brightSlider.setMajorTickSpacing(25);
        brightSlider.setMinorTickSpacing(5);
        brightSlider.setPaintLabels(true);
        brightSlider.setPaintTicks(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brightEnableBox)
                .addGap(18, 18, 18)
                .addComponent(brightSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brightEnableBox)
                    .addComponent(brightSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Invert"));

        invertEnableBox.setText("Invert Colours");
        invertEnableBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertEnableBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invertEnableBox)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invertEnableBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        logo.setIcon(SysIcon.BigAdjust.Icon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(resetButton)
                            .addComponent(okButton))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brightEnableBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brightEnableBoxActionPerformed
        // TODO add your handling code here:
        brightSlider.setEnabled(brightEnableBox.isSelected());
        if(!brightEnableBox.isSelected()) brightSlider.setValue(50);
}//GEN-LAST:event_brightEnableBoxActionPerformed

    private void invertEnableBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertEnableBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_invertEnableBoxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        //Revert slider positions etc? or Set them when reopened?
        setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        brightness = brightSlider.getValue();
        contrast = contrastSlider.getValue();
        inverted = invertEnableBox.isSelected();
        setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed
public int getCurrentSliderBright(){
    return brightSlider.getValue();
}
public int getCurrentSliderContrast(){
    return contrastSlider.getValue();
}
public boolean getCurrentInvertBox(){
    return invertEnableBox.isSelected();
}
    private void contrastEnableBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrastEnableBoxActionPerformed
        // TODO add your handling code here:
        contrastSlider.setEnabled(contrastEnableBox.isSelected());
        if(!contrastEnableBox.isSelected()) contrastSlider.setValue(50);
    }//GEN-LAST:event_contrastEnableBoxActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        brightSlider.setEnabled(true);
        contrastSlider.setEnabled(true);
        brightSlider.setValue(50);
        contrastSlider.setValue(50);
        invertEnableBox.setSelected(false);
        resetPressed = true;
        cancelButtonActionPerformed(evt);
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImageAdjuster dialog = new ImageAdjuster(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    void addChangeListeners(ChangeListener l){
        brightSlider.addChangeListener(l);
        contrastSlider.addChangeListener(l);
        invertEnableBox.addChangeListener(l);
        contrastEnableBox.addChangeListener(l);
        brightEnableBox.addChangeListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox brightEnableBox;
    private javax.swing.JSlider brightSlider;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox contrastEnableBox;
    private javax.swing.JSlider contrastSlider;
    private javax.swing.JCheckBox invertEnableBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JButton okButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables

}
